---
contributor_name_type:
  type: string
  form:
    required: false
    multiple: false
    type: select
    authority: Hyku::Plugin::Schema::Yaml::NameTypeService
contributor_family_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Personal
contributor_given_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Personal
contributor_orcid:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Personal
contributor_institutional_relationship:
  type: string
  form:
    required: false
    multiple: false
    type: select
    authority: Hyku::Plugin::Schema::Yaml::ContributorInstitutionalRelationshipService
    attributes:
      multiple: multiple
    display_for:
    - Personal
contributor_organization_name:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Organizational
contributor_ror:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Organizational
contributor_grid:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Organizational
contributor_wikidata:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Organizational
contributor_isni:
  type: string
  form:
    required: false
    multiple: false
    type: text
    display_for:
    - Personal
    - Organizational
contributor_role:
  type: string
  form:
    required: false
    multiple: true
    type: select
    authority: Hyku::Plugin::Schema::Yaml::RoleService
    display_for:
    - Personal
    - Organizational
