terms:
  - term: Advisor
    id:  Advisor
    active: true
  - term: Partner Organization
    id: Partner Organization
    active: true
  - term: Contributor
    id: Contributor
    active: true
  - term: Editor
    id: Editor
    active: true
