terms:
  - id: Conference paper (unpublished)
    term: Conference paper (unpublished)
  - id: Abstract
    term: Abstract
  - id: Conference paper (published)
    term: Conference paper (published)
  - id: Conference poster (published)
    term: Conference poster (published)
  - id: Conference poster (unpublished)
    term: Conference poster (unpublished)
  - id: Lecture
    term: Lecture
  - id: Presentation
    term: Presentation

