terms:
  - id: Uncategorized
    term: Uncategorized
  - id: Application
    term: Application
  - id: Grant
    term: Grant
  - id: J_Correspondence_Transcription
    term: J_Correspondence_Transcription
  - id: O_Address_Transcription
    term: O_Address_Transcription
  - id: Strategy
    term: Strategy
  - id: T_Writings_Transcription
    term: T_Writings_Transcription
  - id: Survey
    term: Survey
