terms:
  - id: Audio
    term: Audio
  - id: Animation
    term: Animation
  - id: Digital creative works
    term: Digital creative works
  - id: Interview (radio, television)
    term: Interview (radio, television)
  - id: Musical composition
    term: Musical composition
  - id: Performance (theatre, dance, musical)
    term: Performance (theatre, dance, musical)
  - id: Podcast
    term: Podcast
  - id: Video
    term: Video

